### ISSUE TITLE
Slight delay after using Alt+a/e/i/o/u + space

### ISSUE THREAD

**Issue by ludalex** [carjorvaz/macos-us-altgr-intl#1]
This layout works perfectly, my only issue after pressing Alt(Option) + any of the vowels, which outputs á é í ó or ú, it adds a slight delay you need to wait in order to  press space the space key  - like it's waiting for something. This makes it very annoying to quickly type those accented characters followed by spaces.

Update: just realized this is caused by the layout supporting key combinations with Alt(Option) + Space, thus forcing you to depress Alt or Space immediately before typing out any other letter.

Any idea why this is happening and how to disable it?

Thanks!

**Comment by carjorvaz** [comment]
I don't know why that's happening to you, especially because it works fine on my setup. I'm able to keep Alt(Option) pressed, type á é í ó or ú and press space (even with Alt(Option) pressed) and it outputs a space character immediately.

I'd check first if this is truly because of the layout file by seeing if you get the same behaviour with the standard layouts in macOS and the layouts to which I link in the README file.
