### ISSUE TITLE
Can't select this layout in the last version of MacOS

### ISSUE THREAD

**Issue by fjfnaranjo** [carjorvaz/macos-us-altgr-intl#2]
Hello! Thanks for the layout!

I've using it for a while, but recently, after a system update, I wasn't able to select it in the menu bar dropdown.

I tried to remove it and adding it again (with restarts) but it doesn't let me select it. It adds it to the list without problems, but I cannot use it.

I've been messing around in the file and I can see a DTD that its installed in the system. I tried to validate the layout against this file and it dropped some errors.

Do you think this may be a possible reason? :thinking: 

My command:

```sudo xmllint --noout --dtdvalid /System/Library/DTDs/KeyboardLayout.dtd /Library/Keyboard Layouts/us-altgr-intl.keylayout```

Head of the reply:

```
/Library/Keyboard Layouts/us-altgr-intl.keylayout:1: parser warning : Unsupported version '1.1'
<?xml version="1.1" encoding="UTF-8"?>
                   ^
/Library/Keyboard Layouts/us-altgr-intl.keylayout:97: parser error : xmlParseCharRef: invalid xmlChar value 8
            <key code="51" output="&#x0008;"/>
                                           ^
/Library/Keyboard Layouts/us-altgr-intl.keylayout:98: parser error : xmlParseCharRef: invalid xmlChar value 3
            <key code="52" output="&#x0003;"/>
                                           ^
/Library/Keyboard Layouts/us-altgr-intl.keylayout:99: parser error : xmlParseCharRef: invalid xmlChar value 27
            <key code="53" output="&#x001B;"/>
                                           ^
```

**Comment by kdevo** [comment]
@fjfnaranjo Which MacOS version are you on? For me it's working without any problem on the newest Sequoia (Darwin). Though the validation is also complaining (same errors). I think this is because the DTD is defined as:

```xml
<!ATTLIST key output CDATA #IMPLIED >
```

Whereas in the XML version 1.0 which xmllint seems to use, the [charset for `CDATA` is defined as](https://www.w3.org/TR/REC-xml/#charsets):

```regexp
#x9 | #xA | #xD | [#x20-#xD7FF] | [#xE000-#xFFFD] | [#x10000-#x10FFFF]
```

and the `#x0008` for example is not in this range.

@carjorvaz Thanks for your work, appreciate it! It's working well so far.
Maybe it's off-topic, but since some of the "incompatible" chars are due to the CTRL layer: When checking it in Ukelele, I was wondering if there is any reason to add the CTRL layer, as the normal layouts do not have it and still can send CTRL+C etc. The keys in the layout of this repo appear to be the default ones for any keyboard, so usually MacOS sends the "right codes" without adding them explicitly (tried it). Just to understand it better, after reading your blog post, was the reason you added them due to better Emacs support?

**Comment by fjfnaranjo** [comment]
@kdevo I'm still on Sonoma. I will try to upgrade. Thanks!

**Comment by carjorvaz** [comment]
> @carjorvaz Thanks for your work, appreciate it! It's working well so far. Maybe it's off-topic, but since some of the "incompatible" chars are due to the CTRL layer: When checking it in Ukelele, I was wondering if there is any reason to add the CTRL layer, as the normal layouts do not have it and still can send CTRL+C etc. The CTRL layer keys in the layout of this repo appear to be the default ones for any keyboard, so usually MacOS sends the "right codes" without adding them explicitly (tried it). Just to understand it better, after reading your blog post, was the motivation you added them due to better Emacs support?

If I recall correctly, the layout I was using previously did not have the CTRL layer and although it did work with regular Emacs, I wasn't able to use CTRL bindings in the Emacs "Mac port" version.
